services:
  mysql57:
    image: "mysql:5.7.42-debian"
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    restart: always
    networks:
      - mysql-network
  mysql80:
    image: "mysql:8.0.28-debian"
    platform: linux/amd64
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge
